name: Test

on:
    pull_request:
        branches:
            - main
jobs:
    greeting:
        runs-on: ubuntu-lates
        steps:
            - name: Say Hello!
            run: echo "Hello from the pipeline! "

